/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.kubeiwu.commontool;

public final class R {
	public static final class id {
		public static int pager = 0x7f020001;
		public static int realtabcontent = 0x7f020000;
	}
}
